const ImageActionTypes = {
  PHOTOS_FETCHED: "PHOTOS_FETCHED",
  PHOTOS_UPLOADED: "PHOTOS_UPLOADED",
  DELETE_UPLOADED_PHOTO: "DELETE_UPLOADED_PHOTO",
  UPDATE_UPLOADED_PHOTO: "UPDATE_UPLOADED_PHOTO",
};

export default ImageActionTypes;
